/**
 * API client. Talks to the FastAPI backend with httpOnly cookie credentials.
 *
 * All shapes come from `lib/api/types.gen.ts`, which is regenerated by
 * `npm run gen:api` against the live backend's OpenAPI schema. If the backend
 * adds/renames a field, regenerate types and the compiler surfaces every
 * affected caller.
 */

import type { components } from "./api/types.gen";

const API_URL =
  process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000/api/v1";

// ─── Public aliases over the generated schemas ────────────────────────────────
export type User = components["schemas"]["UserOut"];
export type SignupInput = components["schemas"]["SignupRequest"];
export type LoginInput = components["schemas"]["LoginRequest"];
export type Problem = components["schemas"]["ProblemRead"];
export type ProblemListResponse = components["schemas"]["ProblemListResponse"];
export type Difficulty = components["schemas"]["Difficulty"];

export type Diagram = components["schemas"]["Diagram"];
export type DiagramNode = components["schemas"]["DiagramNode"];
export type DiagramEdge = components["schemas"]["DiagramEdge"];
export type Submission = components["schemas"]["SubmissionRead"];
export type SubmissionCreate = components["schemas"]["SubmissionCreate"];
export type SubmissionUpdate = components["schemas"]["SubmissionUpdate"];
export type SubmissionListResponse = components["schemas"]["SubmissionListResponse"];
export type EvaluationStatus = components["schemas"]["EvaluationStatus"];

// ─── Errors ───────────────────────────────────────────────────────────────────
export class ApiError extends Error {
  constructor(
    public status: number,
    public detail: string,
  ) {
    super(`${status} ${detail}`);
    this.name = "ApiError";
  }
}

// ─── Core fetch wrapper ───────────────────────────────────────────────────────
async function apiFetch<T>(
  path: string,
  options: RequestInit = {},
): Promise<T> {
  const res = await fetch(`${API_URL}${path}`, {
    ...options,
    // Send + receive httpOnly cookies cross-origin (dev: 3000 → 8000)
    credentials: "include",
    headers: {
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });

  if (!res.ok) {
    let detail = res.statusText;
    try {
      const body = (await res.json()) as { detail?: string };
      if (body.detail) detail = body.detail;
    } catch {
      // body wasn't JSON — keep statusText
    }
    throw new ApiError(res.status, detail);
  }

  if (res.status === 204) return undefined as T;
  return (await res.json()) as T;
}

// ─── Auth endpoints ───────────────────────────────────────────────────────────
export const auth = {
  signup: (input: SignupInput) =>
    apiFetch<User>("/auth/signup", {
      method: "POST",
      body: JSON.stringify(input),
    }),

  login: (email: string, password: string) =>
    apiFetch<User>("/auth/login", {
      method: "POST",
      body: JSON.stringify({ email, password } satisfies LoginInput),
    }),

  me: () => apiFetch<User>("/auth/me"),

  logout: () => apiFetch<void>("/auth/logout", { method: "POST" }),

  refresh: () => apiFetch<User>("/auth/refresh", { method: "POST" }),
};

// ─── Problems endpoints ───────────────────────────────────────────────────────
export interface ListProblemsParams {
  difficulty?: Difficulty;
  tags?: string[];
  cursor?: string;
  limit?: number;
}

export const problems = {
  list: (params: ListProblemsParams = {}) => {
    const qs = new URLSearchParams();
    if (params.difficulty) qs.set("difficulty", params.difficulty);
    if (params.cursor) qs.set("cursor", params.cursor);
    if (params.limit) qs.set("limit", String(params.limit));
    if (params.tags) for (const t of params.tags) qs.append("tags", t);
    const query = qs.toString();
    return apiFetch<ProblemListResponse>(`/problems${query ? `?${query}` : ""}`);
  },

  get: (id: string) => apiFetch<Problem>(`/problems/${encodeURIComponent(id)}`),
};

// ─── Submissions endpoints ────────────────────────────────────────────────────
export interface ListSubmissionsParams {
  problem_id?: string;
  cursor?: string;
  limit?: number;
}

export const submissions = {
  create: (input: SubmissionCreate) =>
    apiFetch<Submission>("/submissions", {
      method: "POST",
      body: JSON.stringify(input),
    }),

  list: (params: ListSubmissionsParams = {}) => {
    const qs = new URLSearchParams();
    if (params.problem_id) qs.set("problem_id", params.problem_id);
    if (params.cursor) qs.set("cursor", params.cursor);
    if (params.limit) qs.set("limit", String(params.limit));
    const query = qs.toString();
    return apiFetch<SubmissionListResponse>(
      `/submissions${query ? `?${query}` : ""}`,
    );
  },

  get: (id: string) =>
    apiFetch<Submission>(`/submissions/${encodeURIComponent(id)}`),

  update: (id: string, input: SubmissionUpdate) =>
    apiFetch<Submission>(`/submissions/${encodeURIComponent(id)}`, {
      method: "PATCH",
      body: JSON.stringify(input),
    }),
};
